title: "Tanguy Colleville"
description: "Quant Researcher | Statistical Arbitrage | Machine Learning"
url: "https://TanguyColleville.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto
  social_links:
    github: Tanguy Colleville
    linkedin: Tanguy Colleville

# Optional (for dark/light mode toggle)
show_excerpts: false

author:
  name: "Tanguy Colleville"
  email: ""