title: "Tanguy Colleville"
description: "Quant Researcher | Statistical Arbitrage | Machine Learning"
remote_theme: mmistakes/minimal-mistakes
markdown: kramdown

plugins:
  - jekyll-include-cache

# Navigation
header_pages:
  - index.md
  - about.md
  - professional.md
  - projects.md

# Social links
social:
  - name: GitHub
    url: https://github.com/yourusername
  - name: LinkedIn
    url: https://www.linkedin.com/in/yourlinkedin
  - name: Email
    url: mailto:your.email@example.com

minimal_mistakes_skin: "neon"
permalink: /:title/
sass:
  style: compressed